
services:
  - type: web
    name: reconhecimento-facial
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DB_NAME
        value: facialdb_fj3i
      - key: DB_USER
        value: adm
      - key: DB_PASSWORD
        value: bdunwFc6lvwAotvqDdKvRX4eDjHspy4a
      - key: DB_HOST
        value: dpg-cvskeq9r0fns73cbad20-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
